### ISSUE TITLE
文案_May20

### ISSUE THREAD

**Issue by derekdylu** [icheft/2020climas-v2#2]
迎新宿營
萬丈高樓平地起，迎新宿營將是你在公館大學生涯的完美起點。在這裡，你將擁有大學四年最難忘的回憶、最刺激的體驗與最浪漫的故事（沒），還不快手刀報名參加！

營隊簡介
<敬請期待>

活動流程
<敬請期待>

下載
<即將開放>

報名
<即將開放>

FAQ
<敬請期待>

**Comment by derekdylu** [comment]
Brian L. Chen
Developer. Owner of icheft.
“網站隨時會更新，記得隨時回來關注，或追蹤臉書粉絲專頁！”

**Comment by icheft** [comment]
Adopted. Thanks.
